# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Codigo')),
                ('picture', models.ImageField(upload_to='pic_folder/')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Disponible')),
                ('notes', models.TextField(verbose_name='Descripcion')),
                ('cost_price', models.PositiveIntegerField(verbose_name='Precio')),
                ('sell_price', models.PositiveIntegerField(verbose_name='Precio Venta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joya.Category')),
            ],
        ),
    ]
