# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost_price',
            field=models.PositiveIntegerField(verbose_name='Precio Costo'),
        ),
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(upload_to='media/pic_folder/'),
        ),
    ]
