# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0003_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio Venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='cost_price',
            field=models.PositiveIntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='items',
            name='sell_price',
            field=models.PositiveIntegerField(verbose_name='Venta'),
        ),
    ]
