# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0004_auto_20170516_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='sales',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='note',
            field=models.TextField(default='', verbose_name='Nota'),
        ),
    ]
