# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0006_auto_20170518_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('website', models.CharField(max_length=200, verbose_name='WebSite')),
            ],
            options={
                'verbose_name': 'Proveedor',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Venta'},
        ),
        migrations.AddField(
            model_name='items',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='joya.Supplier'),
        ),
    ]
