# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0009_auto_20170827_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tallas'),
        ),
    ]
