# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0010_sales_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Nota'),
        ),
    ]
