# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joya', '0011_auto_20170827_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='profit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
